# Generated by Django 4.0.10 on 2023-10-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0006_blogcategory_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='author',
        ),
    ]
