# Generated by Django 4.2.5 on 2023-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0006_remove_blogpost_category_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(blank=True, to='BlogApplication.blogcategory'),
        ),
    ]
