# Generated by Django 4.2.5 on 2023-10-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0007_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pupDate'], 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
