# Generated by Django 4.2.5 on 2023-10-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0008_alter_blogcategory_options_alter_blogpost_options'),
        ('BlogApplication', '0008_blogcategory_author'),
    ]

    operations = [
    ]
