# Generated by Django 4.2.5 on 2023-10-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0010_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
