# Generated by Django 4.0.10 on 2023-10-04 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApplication', '0012_alter_company_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
    ]
