# Generated by Django 4.0.10 on 2023-10-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0013_company_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='employees',
            new_name='writers',
        ),
    ]
